version: '3.1'

services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: mysql
    network_mode: host
    environment:
      MYSQL_ROOT_PASSWORD: ctfadmin1234
      MYSQL_DATABASE: ctfweb
    

  file-injection: 
    image: sleepanda4523/file-injection 
    container_name: file-injection 
    ports: 
      - "3000:3000"
    restart: "always"
    network_mode: host
